# /path/to/your-app/config/http.yaml

# Kunci 'server' adalah top-level, dan 'http' adalah sub-key.
server:
  http:
    host: "127.0.0.1"
    port: "8080"
    read_timeout: "5s"
    write_timeout: "10s"
    idle_timeout: "120s"
    tls:
      enabled: false
      cert_file: ""
      key_file: ""
      tls_version: "TLS1.2"